# Generated by Django 5.2.12 on 2026-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(max_length=255)),
                ("relay", models.BooleanField()),
                ("ldr", models.IntegerField()),
                ("motion", models.BooleanField()),
            ],
        ),
    ]
